### Load grid search data from .csv files to dataframe and write dataframe to a tmp file, to be processed by `process_gridSearch_df.ipynb`.

In [23]:
import numpy as np
import pandas as pd
import scipy.stats

In [24]:
ndRlist = [1, 2, 3, 4, 5, 10, 12, 15, 20, 30, 60, 100, 300]
ndlist = [1, 2, 3, 4, 5, 10, 12, 15, 20, 30, 50, 60, 75, 100, 150, 300, 400, 750, 1000, 1500]
nslist = [60000, 30000, 20000, 15000, 12000, 6000, 5000, 4000, 3000, 2000, 1200, 1000, 800, 600, 400, 200, 150, 80, 60, 40]

In [48]:
# file_path0 = "../data/no_nonlinearity/"
# file_path0 = "../data/gridSearch_standard/60000/coeff_infty/"
# file_path0 = "../data/gridSearch_variableNs/0.99/"
# file_path0 = "../data/gridSearch_StepActivation/60000/coeff_infty/"
# file_path0 = "../data/gridSearch_NonInt/60000/coeff_4/"
# file_path0 = "../data/gridSearch_SomaNoise/coeff_infty/dendrite_noise_0.6/"
# file_path0 = "../data/gridSearch_SynapseNoise/60000/coeff_infty/noise_0.3/"
# file_path0 = "../data/gridSearch_int_variable_n_min1/60000/coeff_infty/"
file_path0 = "../tmp_data/int_variable_n_min1/"

0.5, .2, .25, .3

(0.5, 0.2, 0.25, 0.3)

In [52]:
n_trials  = 6

df = pd.DataFrame(data=None)
for nd_idx, nd in enumerate(ndlist):
    for i, ndR in enumerate(ndRlist):
        tmp_df = pd.DataFrame(data=None)
        try:
            ns=nslist[nd_idx]
            # tmp_array = np.genfromtxt(f"{file_path0}nd{nd}_ns{ns}/ndR{ndR}.csv", delimiter=',')
            tmp_array = np.genfromtxt(f"{file_path0}nd{nd}_ns{ns}/n{ndR}.csv", delimiter=',')
            n_rows = tmp_array.shape[0]
            tmp_df.insert(0, "nd", np.ones(n_rows)*nd)
            tmp_df.insert(1, "ndR", np.ones(n_rows)*ndR)
            tmp_df.insert(2, "b", tmp_array[:, 0])
            tmp_df.insert(3, "bk", tmp_array[:, 1])
            tmp_df.insert(4, "beta", tmp_array[:, 2])
            tmp_array_mean = np.mean(tmp_array[:, -n_trials:], axis=1)
            tmp_array_sem = scipy.stats.sem(tmp_array[:, -n_trials:], axis=1)
            tmp_df.insert(5, "capacity", tmp_array_mean)
            tmp_df.insert(6, "sem", tmp_array_sem)
            df = pd.concat([df, tmp_df], ignore_index=True)
        except:
            pass

In [53]:
df.to_csv("../tmp_data/plot_data/tmp_df.csv", index=False)

In [54]:
df

          nd  ndR     b    bk       beta     capacity         sem
0        1.0  1.0  1.80  5.75  16.033676     0.000000    0.000000
1        1.0  1.0  1.95  5.75  16.033676     0.000000    0.000000
2        1.0  1.0  2.10  5.75  16.033676     0.000000    0.000000
3        1.0  1.0  2.25  5.75  16.033676     0.000000    0.000000
4        1.0  1.0  2.40  5.75  16.033676  1029.985000  206.517942
...      ...  ...   ...   ...        ...          ...         ...
4243  1000.0  2.0  4.05  5.25  11.545334     0.000000    0.000000
4244  1000.0  2.0  4.20  5.25  11.597037     0.000000    0.000000
4245  1000.0  2.0  4.35  5.25  11.657735   269.166667   12.501778
4246  1000.0  2.0  4.50  5.25  11.727485   226.333333   12.057271
4247  1000.0  2.0  4.65  5.25  11.806350   131.000000    5.125102

[4248 rows x 7 columns]

In [55]:
tmp_df

Empty DataFrame
Columns: []
Index: []